[build]
  # 1. Use the existing 'build' script (or the new 'build:client' script)
  # 2. Add 'CI=' to prevent warnings from failing the build
  command = "npm install && CI= npm run build" 
  # OR command = "npm install && CI= npm run build:client" if you made the package.json change
  
  # Vite outDir is configured to 'dist/public' in vite.config.ts
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev" # Changed from dev:client to dev to match package.json
  port = 5173